#!/usr/bin/python3

import os
import sys
import subprocess
import re
from git import Repo


dir_list = os.getcwd()
cmd = "git diff -U0 --no-color --staged  HEAD --$dir_list | clang-format-diff -p1 -style=file"

print("\n \033[3;34;34m Checking for style differences...\033[0;0m \n")

repo = Repo('.', search_parent_directories=True)
reader = repo.config_reader()
# Gets the mode assigned by the user in the git config file.
mode = str(reader.get_value("style","mode"))

# Execute the format command
diff = subprocess.getoutput(cmd)


# This is for the default mode which prints out the number of issues
# and warnings in case there are style mismatches
def nonStrict():
    output = diff.split("\n")
    files = []
    num_diff = 0
    for line in output:
        if line.startswith("+++"):
            file = str(re.sub('[+]', '', line))
            file = file.replace("(after formatting)", "").strip()
            files.append(file)
            output.remove(line)
        elif line.startswith("+"):
            num_diff += 1
    print("\033[1;33;33m Files affected: \033[0;0m")
    for file in files:
        print(file)
    print("")
    message = "You have about a total of " + str(num_diff) + " style issue(s) in the " + \
        str(len(files)) + " file(s) listed above"
    print("\033[1;31;33m" + "StyleWarning: " + message + "\033[0;0m")

# This is for the strict mode which prints out a more detailed report
#  of issuse and warnings in case there are style mismatches
def strict():
    output = diff.split("\n")
    files = []
    num_diff = 0
    for line in output:
        if line.startswith("+"):
            num_diff += 1
            print("\033[1;34;34m" + line + "\033[0;0m")
        else:
            print(line)
        if line.startswith("+++"):
            file = str(re.sub('[+]', '', line))
            file = file.replace("(after formatting)", "").strip()
            files.append(file)
            output.remove(line)
    print("\033[1;33;33m Files affected: \033[0;0m")
    for file in files:
        print(file)
    print("")
    message = "You have about a total of " + str(num_diff) + " style issue(s) in the " + \
        str(len(files)) + " file(s) listed above"
    print("\033[1;31;33m" + "StyleWarning: " + message + "\033[0;0m")


# Print the outcome
if len(diff) == 0:
    print("\033[1;34;34m Everything is clean - style matches RTEMS \033[0;0m")
    sys.exit(0)
elif mode == "strict":
    strict()
    print("")
    print("\033[1;31;31m ERROR: Commit aborted due to code format inconsistencies" \
        "with RTEMS \033[0;0m")
    sys.exit(1)
elif mode == "nonstrict":
    nonStrict()
    sys.exit(0)
else:
    nonStrict()
    print("")
    print("\033[1;31;31m ERROR: Commit aborted due to code format inconsistencies with" \
        " RTEMS \033[0;0m ")
    sys.exit(1)
